start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\un.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\deux.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\trois.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\quatre.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\cinq.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\seis.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\sept.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\huit.py
start C:\Users\ddouglas\AppData\Local\Programs\Python\Python37-32\Emma-Customer\neuf.py